package com.example.identifiers;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

import java.util.UUID;

/**
 * Note 11 — UUID primary keys.
 * Useful when ids must be unique across systems or generated by the application before insert.
 * With a {@code UUID} field, Hibernate 6 uses the UUID generation strategy automatically.
 */
@Entity
@Table(name = "id_uuid")
@Getter
@Setter
@NoArgsConstructor
@ToString
public class UuidEntity {

    @Id
    @GeneratedValue
    private UUID id;

    private String label;

    public UuidEntity(String label) {
        this.label = label;
    }
}
